@url=http://localhost:8001/api/user
@json=Content-Type: application/json


### 用户注册
post {{url}}/register
{{json}}

{
  "username": "yaogengzhu233",
  "password": "123456"
}



### 用户登录
post {{url}}/login
{{json}}

{
  "username": "yaogengzhu23",
  "password": "123456"
}

### 获取用户信息

get {{url}}/userInfo

### 退出登录
POST {{url}}/logout