version: '3.8'
services:
  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: api-v1
    container_name: api-v1
    ports:
      - 8001:8001
    environment:
      - TZ=Asia/Shanghai # 时区设置为东八区
    volumes:
      - .:/app
