version: '3.8'
services:
  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: api:1.0.0
    container_name: api
    ports:
      - 8000:8000
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
