version: '3.8'
services:
  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: api
    container_name: api
    ports:
      - 8001:8001
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
