@url=http://localhost:8001/api/order
@json=Content-Type: application/json

### 获取订单列表

get {{url}}/list?status=1&page=1&pageSize=10


### 用户下单

post {{url}}/purchase
{{json}}

{
  "address_id": 11,
  "goods_list": [{ "goods_id": 2, "count": 400}, { "goods_id": 2, "count": 100}],
  "total_price": 300
}

### 用户付款

post {{url}}/pay
{{json}}

{
  "order_no": "23060300008"
}


### 用户确认收货

post {{url}}/confirm
{{json}}

{
  "order_no": "23060300008"
}